name: "Create GMUD"
description: "Create GMUD"
inputs:
  domain:
    description: "url jira"
    required: true
  basic-auth:
    description: "jira authentication"
    required: true
  api-key:
    description: "jira api key"
    required: true
  auth-github:
    description: "github authentication"
    required: true
  service-desk-id:
    description: "service desk id"
    required: true
  request-type-id:
    description: "request type id"
    required: true
  service:
    description: "service"
    required: true
  technical-approval:
    description: "technical approval"
    required: true
  business-approval:
    description: "business approval"
    required: true
  url-pull-request:
    description: "url pull request"
    required: true
  url-slifer-gmud:
    description: "url create servicedesk"
    required: true
outputs:
  result:
    description: "finished process"
runs:
  using: "node12"
  main: "dist/index.js"
